// apps/web/app/components/HeroSection.vue
<script setup lang="ts">
const { t } = useI18n();
</script>

<template>
  <section class="relative min-h-screen flex items-center overflow-hidden pt-28 pb-20">
    <!-- Background Image Overlay with Gradient Fade -->
    <div class="absolute inset-0 pointer-events-none overflow-hidden">
      <img
        :src="'/images/hero-bg.png'"
        alt="Amertarva Agency Workstation"
        class="w-full h-full object-cover opacity-20 dark:opacity-25 mix-blend-multiply dark:mix-blend-luminosity filter blur-[0.5px] scale-105"
      />
      <div class="absolute inset-0 bg-gradient-to-b from-base/50 via-base/30 to-base" />
    </div>

    <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full">
      <div class="max-w-4xl">
        <!-- Main Title -->
        <Motion
          :initial="{ opacity: 0, y: 30 }"
          :animate="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6, delay: 0.1, ease: 'easeOut' }"
        >
          <h1 class="text-4xl sm:text-6xl lg:text-7xl font-extrabold tracking-tight leading-[1.08] mb-8 text-heading">
            {{ t('hero.titleStart') }}
            <span class="text-accent underline underline-offset-8 decoration-accent/30">{{ t('hero.titleHighlight') }}</span>
            {{ t('hero.titleEnd') }}
          </h1>
        </Motion>

        <!-- Subtitle -->
        <Motion
          :initial="{ opacity: 0, y: 30 }"
          :animate="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6, delay: 0.2, ease: 'easeOut' }"
        >
          <p class="text-lg sm:text-xl text-body max-w-2xl mb-10 leading-relaxed font-normal">
            {{ t('hero.description') }}
          </p>
        </Motion>

        <!-- Action CTAs -->
        <Motion
          :initial="{ opacity: 0, y: 30 }"
          :animate="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6, delay: 0.3, ease: 'easeOut' }"
        >
          <div class="flex flex-wrap items-center gap-4 mb-14">
            <a
              href="#contact"
              class="inline-flex items-center gap-2.5 bg-accent hover:bg-accent/90 text-accent-contrast font-sans text-sm font-semibold px-7 py-3.5 rounded-xl transition-all duration-300 hover:-translate-y-0.5"
            >
              {{ t('hero.ctaPrimary') }}
            </a>
            <a
              href="#services"
              class="inline-flex items-center gap-2.5 border border-border/80 hover:border-accent/40 bg-secondary/10 hover:bg-secondary/20 font-sans text-sm font-semibold px-7 py-3.5 rounded-xl transition-all duration-300"
            >
              <span class="text-heading">{{ t('hero.ctaSecondary') }}</span>
            </a>
          </div>
        </Motion>

        <!-- Metrics Stats Counter Grid -->
        <Motion
          :initial="{ opacity: 0, y: 30 }"
          :animate="{ opacity: 1, y: 0 }"
          :transition="{ duration: 0.6, delay: 0.4, ease: 'easeOut' }"
        >
          <div class="grid grid-cols-3 gap-4 pt-8 border-t border-border/80 max-w-2xl">
            <div class="pr-4 border-r border-border/80">
              <div class="text-2xl sm:text-3xl font-mono font-extrabold text-heading">100+</div>
              <div class="text-xs text-body font-medium uppercase tracking-wider mt-1">{{ t('hero.stats.projects') }}</div>
            </div>
            <div class="px-2 pr-4 border-r border-border/80">
              <div class="text-2xl sm:text-3xl font-mono font-extrabold text-heading">10+</div>
              <div class="text-xs text-body font-medium uppercase tracking-wider mt-1">{{ t('hero.stats.clients') }}</div>
            </div>
            <div class="pl-2">
              <div class="text-2xl sm:text-3xl font-mono font-extrabold text-accent">5+</div>
              <div class="text-xs text-body font-medium uppercase tracking-wider mt-1">{{ t('hero.stats.experience') }}</div>
            </div>
          </div>
        </Motion>
      </div>
    </div>
  </section>
</template>

// apps/elearning/src/components/home/hero/HeroSection.jsx
import { MessageCircle, ShieldCheck } from 'lucide-preact';

export default function HeroSection() {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-background">
      {/* Background Image with Gradient Overlay */}
      <div className="absolute inset-0 z-0">
        <img 
          src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop" 
          alt="Profesional E-Learning" 
          className="w-full h-full object-cover opacity-80"
        />
        {/* Complex gradient to give a premium, deep dark look */}
        <div className="absolute inset-0 bg-linear-to-r from-background via-background/80 to-transparent"></div>
        <div className="absolute inset-0 bg-linear-to-t from-background via-transparent to-background/30"></div>
      </div>

      <div className="container relative z-10 mx-auto px-6 md:px-12 flex flex-col lg:flex-row items-center pt-24 pb-12">
        {/* Main Text Content */}
        <div className="w-full lg:w-2/3 xl:w-3/5 text-left">

          {/* Headline */}
          <h1 className="text-4xl md:text-5xl lg:text-7xl font-bold text-heading leading-tight mb-6 font-serif">
            Transformasi Digital <br className="hidden md:block" />
            <span className="text-primary">
              Sekolah Tanpa Batas
            </span>
          </h1>

          {/* Sub-headline / Tagline */}
          <p className="text-lg md:text-xl text-paragraph mb-10 max-w-2xl leading-relaxed">
            Amertarva menyewakan platform Learning Management System (LMS) berlabel putih (White-label) mutakhir untuk Sekolah, Bimbingan Belajar, dan Layanan Pendidikan guna mengakselerasi digitalisasi institusi Anda.
          </p>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row items-center gap-4 mb-14">
            <a 
              href="#program" 
              className="w-full sm:w-auto px-8 py-4 rounded-full bg-primary hover:bg-primary/90 text-background font-bold transition-all duration-300 flex items-center justify-center gap-2 hover:-translate-y-1"
            >
              Pelajari Selengkapnya
            </a>
            
            <a 
              href="#konsultasi" 
              className="w-full sm:w-auto px-8 py-4 rounded-full bg-heading/5 hover:bg-heading/10 border border-heading/10 text-heading font-semibold transition-all duration-300 flex items-center justify-center gap-2 backdrop-blur-md hover:-translate-y-1"
            >
              Konsultasi Gratis
              <MessageCircle className="w-5 h-5" />
            </a>
          </div>


        </div>
      </div>
      
      
      {/* Seamless Transition Gradient to About Section */}
      <div className="absolute bottom-0 left-0 right-0 h-40 bg-linear-to-t from-background via-background/80 to-transparent pointer-events-none z-0"></div>
    </section>
  );
}
