// apps/elearning/src/components/home/layouts/navbar.jsx
import { useState, useEffect } from 'preact/hooks';
import { Sun, Moon, Languages, Menu, X } from 'lucide-preact';

export default function Navbar() {
  const [isScrolled, setIsScrolled] = useState(false);
  // Default to dark since we added class="dark" to html initially
  const [theme, setTheme] = useState('dark');
  const [lang, setLang] = useState('id');
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 20);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === 'dark' ? 'light' : 'dark';
    setTheme(newTheme);
    if (newTheme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  };

  const navLinks = [
    { name: 'Beranda', href: '#' },
    { name: 'Tentang Kami', href: '#tentang-kami' },
    { name: 'Alur', href: '#alur' },
    { name: 'Kerjasama', href: '#harga' },
  ];

  return (
    <header
      className={`fixed top-0 left-1/2 -translate-x-1/2 z-50 transition-all duration-500 w-full md:w-[90%] max-w-[1200px] ${
        isScrolled
          ? 'bg-background/80 backdrop-blur-md shadow-lg border border-t-0 border-heading/10 rounded-b-[2.5rem] py-4'
          : 'bg-transparent py-6 border border-transparent'
      }`}
    >
      <div className="container mx-auto px-6 md:px-12 flex items-center justify-between">
        {/* Logo */}
        <a href="#" className="flex items-center gap-2 group z-50">
          <div className="relative flex items-center">
            <span className="text-2xl font-serif tracking-wide text-primary transition-colors">
              amertar
            </span>
            <div className="relative flex flex-col items-center justify-center">
              <Sun className="w-5 h-5 text-secondary absolute -top-3.5 opacity-90 group-hover:opacity-100 group-hover:rotate-45 transition-all duration-500" />
              <span className="text-2xl font-serif tracking-wide text-primary transition-colors">
                v
              </span>
            </div>
            <span className="text-2xl font-serif tracking-wide text-primary transition-colors">
              a
            </span>
          </div>
        </a>

        {/* Desktop Navigation */}
        <nav className="hidden md:flex items-center gap-8">
          {navLinks.map((link) => (
            <a
              key={link.name}
              href={link.href}
              className="text-[15px] font-medium text-paragraph hover:text-heading transition-colors relative after:absolute after:-bottom-1 after:left-0 after:h-[2px] after:w-0 after:bg-primary after:transition-all after:duration-300 hover:after:w-full"
            >
              {link.name}
            </a>
          ))}
        </nav>

        {/* Actions (Desktop) */}
        <div className="hidden md:flex items-center gap-4">
          <button
            onClick={toggleTheme}
            className="p-2.5 rounded-full bg-heading/5 hover:bg-heading/10 border border-heading/10 text-paragraph hover:text-heading transition-all duration-300 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-primary/50"
            aria-label="Toggle Theme"
          >
            {theme === 'dark' ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
          </button>
          
          <button
            onClick={() => setLang(lang === 'id' ? 'en' : 'id')}
            className="p-2.5 rounded-full bg-heading/5 hover:bg-heading/10 border border-heading/10 text-paragraph hover:text-heading transition-all duration-300 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-primary/50 flex items-center justify-center"
            aria-label="Toggle Language"
            title="Switch Language"
          >
            <Languages className="w-4 h-4" />
          </button>
        </div>

        {/* Mobile Menu Toggle */}
        <button
          onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
          className="md:hidden p-2 text-paragraph hover:text-heading transition-colors z-50"
          aria-label="Toggle Menu"
        >
          {isMobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
        </button>
      </div>

      {/* Mobile Navigation */}
      <div
        className={`md:hidden fixed inset-0 bg-background/95 backdrop-blur-xl transition-all duration-500 flex flex-col items-center justify-center gap-8 ${
          isMobileMenuOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'
        }`}
      >
        <nav className="flex flex-col items-center gap-6 text-center">
          {navLinks.map((link) => (
            <a
              key={link.name}
              href={link.href}
              onClick={() => setIsMobileMenuOpen(false)}
              className="text-2xl font-medium text-paragraph hover:text-primary transition-colors"
            >
              {link.name}
            </a>
          ))}
        </nav>
        
        <div className="flex items-center gap-6 mt-4">
          <button
            onClick={toggleTheme}
            className="p-4 rounded-full bg-heading/10 text-heading transition-all hover:bg-heading/20"
          >
            {theme === 'dark' ? <Sun className="w-6 h-6" /> : <Moon className="w-6 h-6" />}
          </button>
          
          <button
            onClick={() => setLang(lang === 'id' ? 'en' : 'id')}
            className="p-4 rounded-full bg-heading/10 text-heading transition-all hover:bg-heading/20 flex items-center gap-2"
          >
            <Languages className="w-6 h-6" />
            <span className="font-bold uppercase">{lang}</span>
          </button>
        </div>
      </div>
    </header>
  );
}

// apps/web/app/components/Navbar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed } from 'vue'
import { Menu, X, Cpu } from 'lucide-vue-next'

const { theme, toggleTheme, initTheme } = useTheme();
const { t, locale, initLocale } = useI18n();

onMounted(() => {
  initTheme();
  initLocale();
});

const isScrolled = ref(false);

const handleScroll = () => {
  isScrolled.value = window.scrollY > 20;
};

onMounted(() => {
  window.addEventListener('scroll', handleScroll);
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});

const navLinks = computed(() => [
  { label: t('nav.about'), href: '/#about' },
  { label: t('nav.services'), href: '/#services' },
  { label: locale.value === 'en' ? 'Workflow' : 'Alur Kerja', href: '/#process' },
  { label: locale.value === 'en' ? 'Portfolio' : 'Portofolio', href: '/#work' },
  { label: t('nav.contact'), href: '/#contact' },
]);

const mobileMenuOpen = ref(false);
</script>

<template>
  <nav
    class="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
    :class="
      isScrolled
        ? 'bg-base/85 backdrop-blur-xl border-b border-border shadow-sm'
        : 'bg-base/60 backdrop-blur-md border-b border-border/40'
    "
  >
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16 lg:h-20">
        <!-- Logo -->
        <NuxtLink to="/" class="flex items-center gap-3 group">
          <div
            class="w-9 h-9 rounded-lg bg-accent/10 border border-accent/30 flex items-center justify-center text-accent transition-all duration-300 group-hover:bg-accent group-hover:text-accent-contrast"
          >
            <Cpu class="w-5 h-5" />
          </div>
          <div class="flex flex-col">
            <span class="text-heading font-extrabold text-base tracking-tight transition-colors duration-200 group-hover:text-accent">
              AMERTARVA
            </span>
            <span class="text-[9px] font-mono tracking-widest text-body/60 uppercase">Tech Agency</span>
          </div>
        </NuxtLink>

        <!-- Desktop Nav -->
        <div class="hidden md:flex items-center gap-1">
          <a
            v-for="link in navLinks"
            :key="link.href"
            :href="link.href"
            class="relative px-3.5 py-2 text-xs font-semibold uppercase tracking-wider text-body hover:text-heading transition-all duration-200 rounded-md hover:bg-secondary/10"
          >
            {{ link.label }}
          </a>
        </div>

        <!-- Desktop Actions -->
        <div class="hidden md:flex items-center gap-3">
          <LocaleToggle />
          <ThemeToggle />
          <a
            href="/#contact"
            class="inline-flex items-center gap-2 bg-accent hover:bg-accent/90 text-accent-contrast font-sans text-xs font-semibold uppercase tracking-wider px-5 py-2.5 rounded-xl transition-all duration-300 hover:-translate-y-0.5"
          >
            {{ t('nav.getInTouch') }}
          </a>
        </div>

        <!-- Mobile Menu Button -->
        <button
          type="button"
          class="md:hidden p-2 text-body hover:text-heading transition-colors"
          @click="mobileMenuOpen = !mobileMenuOpen"
          aria-label="Toggle Menu"
        >
          <X v-if="mobileMenuOpen" class="w-6 h-6" />
          <Menu v-else class="w-6 h-6" />
        </button>
      </div>
    </div>

    <!-- Mobile Menu -->
    <Transition
      enter-active-class="transition duration-200 ease-out"
      enter-from-class="opacity-0 -translate-y-2"
      enter-to-class="opacity-100 translate-y-0"
      leave-active-class="transition duration-150 ease-in"
      leave-from-class="opacity-100 translate-y-0"
      leave-to-class="opacity-0 -translate-y-2"
    >
      <div
        v-if="mobileMenuOpen"
        class="md:hidden bg-base/95 backdrop-blur-lg border-b border-secondary/10"
      >
        <div class="px-6 py-6 space-y-3">
          <a
            v-for="link in navLinks"
            :key="link.href"
            :href="link.href"
            class="block px-4 py-3 text-sm font-semibold text-body hover:text-heading hover:bg-secondary/10 rounded-xl transition-all duration-200"
            @click="mobileMenuOpen = false"
          >
            {{ link.label }}
          </a>

          <div class="flex items-center gap-4 pt-4 border-t border-secondary/10">
            <LocaleToggle />
            <ThemeToggle />
            <a
              href="/#contact"
              class="flex-1 inline-flex items-center justify-center gap-1.5 text-center bg-accent hover:bg-accent/90 text-accent-contrast font-semibold text-sm px-5 py-3 rounded-xl transition-all duration-300"
              @click="mobileMenuOpen = false"
            >
              {{ t('nav.getInTouch') }}
            </a>
          </div>
        </div>
      </div>
    </Transition>
  </nav>
</template>
